// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQqopFw1Qc4676LwRTkGw3FrEiYnHeJGQ',
    appId: '1:201026396296:android:a3d9e7a219dba4175f3f3d',
    messagingSenderId: '201026396296',
    projectId: 'cafeadisyon-ead4c',
    storageBucket: 'cafeadisyon-ead4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXv0WhFVmte-QPMOtmqMfcqjvnIJ3r5BA',
    appId: '1:201026396296:ios:35c58f79ebf80b665f3f3d',
    messagingSenderId: '201026396296',
    projectId: 'cafeadisyon-ead4c',
    storageBucket: 'cafeadisyon-ead4c.appspot.com',
    iosClientId: '201026396296-lp213ap1sgral97ddtbf903hi6bljqhv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeAdisyon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXv0WhFVmte-QPMOtmqMfcqjvnIJ3r5BA',
    appId: '1:201026396296:ios:35c58f79ebf80b665f3f3d',
    messagingSenderId: '201026396296',
    projectId: 'cafeadisyon-ead4c',
    storageBucket: 'cafeadisyon-ead4c.appspot.com',
    iosClientId: '201026396296-lp213ap1sgral97ddtbf903hi6bljqhv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeAdisyon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZVng5BMoUJQUPNfBpixf85ycn1Sap_YM',
    appId: '1:201026396296:web:5c3a8a2fc3abfd955f3f3d',
    messagingSenderId: '201026396296',
    projectId: 'cafeadisyon-ead4c',
    authDomain: 'cafeadisyon-ead4c.firebaseapp.com',
    storageBucket: 'cafeadisyon-ead4c.appspot.com',
    measurementId: 'G-PCLPY07VVE',
  );

}